name: CI Pipeline da Prova (TypeScript)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configura a versão do Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      # 2. Instalação das dependências
      - name: Instalar dependências
        run: npm install

      # 3. Execução dos testes automatizados
      # O "npm test" agora vai usar o ts-jest automaticamente
      - name: Executar testes
        run: npm test
